/*
 * Copyright 2024 The Tongsuo Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://github.com/Tongsuo-Project/Tongsuo/blob/master/LICENSE.txt
 */

/*
 * NOTE: this file was auto generated by the script: e_sdf_err.h
 * Any changes made to this file will be overwritten when the script is next run
 */

#include <openssl/err.h>
#include <stdlib.h>
#include "e_sdf_err.h"

#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(0,func,0)
# define ERR_REASON(reason) ERR_PACK(0,0,reason)

static ERR_STRING_DATA SDF_str_functs[] = {
    {ERR_FUNC(SDF_F_SDF_INIT), "sdf_init"},
    {ERR_FUNC(SDF_F_SDF_FINISH), "sdf_finish"},
    {ERR_FUNC(SDF_F_SDF_CTRL), "sdf_ctrl"},
    {ERR_FUNC(SDF_F_SDF_LOAD_PRIVKEY), "sdf_load_privkey"},
    {ERR_FUNC(SDF_F_SDF_LOAD_PUBKEY), "sdf_load_pubkey"},
    {ERR_FUNC(SDF_F_SDF_RSA_PRIV_ENC), "sdf_rsa_priv_enc"},
    {ERR_FUNC(SDF_F_SDF_RSA_PRIV_DEC), "sdf_rsa_priv_dec"},
    {ERR_FUNC(SDF_F_SDF_RSA_PUB_ENC), "sdf_rsa_pub_enc"},
    {ERR_FUNC(SDF_F_SDF_RSA_PUB_DEC), "sdf_rsa_pub_dec"},
    {ERR_FUNC(SDF_F_SDF_ECC_SIGN), "sdf_ecc_sign"},
    {ERR_FUNC(SDF_F_SDF_ECC_VERIFY), "sdf_ecc_verify"},
    {ERR_FUNC(SDF_F_SDF_SM2_SIGN), "sdf_sm2_sign"},
    {ERR_FUNC(SDF_F_SDF_SM2_VERIFY), "sdf_sm2_verify"},
    {ERR_FUNC(SDF_F_SDF_SM2_ENCRYPT), "sdf_sm2_encrypt"},
    {ERR_FUNC(SDF_F_SDF_SM2_DECRYPT), "sdf_sm2_decrypt"},
    {ERR_FUNC(SDF_F_SDF_RAND_BYTES), "sdf_rand_bytes"},
    {ERR_FUNC(SDF_F_SDF_DIGEST_INIT), "sdf_digest_init"},
    {ERR_FUNC(SDF_F_SDF_DIGEST_UPDATE), "sdf_digest_update"},
    {ERR_FUNC(SDF_F_SDF_DIGEST_FINAL), "sdf_digest_final"},
    {ERR_FUNC(SDF_F_SDF_CIPHER_INIT), "sdf_cipher_init"},
    {ERR_FUNC(SDF_F_SDF_CIPHER_UPDATE), "sdf_cipher_update"},
    {ERR_FUNC(SDF_F_SDF_CIPHER_FINAL), "sdf_cipher_final"},
    {ERR_FUNC(SDF_F_BIND_SDF), "bind_sdf"},
    {ERR_FUNC(SDF_F_CIPHER_SM4_CBC_CIPHER), "cipher_sm4_cbc_cipher"},
    {ERR_FUNC(SDF_F_CIPHER_SM4_ECB_CIPHER), "cipher_sm4_ecb_cipher"},
    {ERR_FUNC(SDF_F_LOAD_KEY), "load_key"},
    {ERR_FUNC(SDF_F_SDF_D2I_ECCCIPHER), "sdf_d2i_ecccipher"},
    {ERR_FUNC(SDF_F_SDF_SM2CIPHERTEXTVALUE_GET_ECCCIPHER), "sdf_sm2ciphertextvalue_get_ecccipher"},
    {0, (const char *)0}
};

static ERR_STRING_DATA SDF_str_reasons[] = {
    {ERR_REASON(SDF_R_ALREADY_LOADED), "already loaded"},
    {ERR_REASON(SDF_R_BN_CTX_FULL), "bn ctx full"},
    {ERR_REASON(SDF_R_BN_EXPAND_FAIL), "bn expand fail"},
    {ERR_REASON(SDF_R_CANT_LOAD_SDF_MODULE), "can't load sdf module"},
    {ERR_REASON(SDF_R_CTRL_COMMAND_NOT_IMPLEMENTED), "ctrl command not implemented"},
    {ERR_REASON(SDF_R_DSO_FAILURE), "dso failure"},
    {ERR_REASON(SDF_R_ENGINE_IS_NOT_INITIALIZED), "engine is not initialized"},
    {ERR_REASON(SDF_R_FUNCTION_NOT_SUPPORTED), "function not supported"},
    {ERR_REASON(SDF_R_INVALID_ARGUMENT), "invalid argument"},
    {ERR_REASON(SDF_R_INVALID_DIGEST_LENGTH), "invalid digest length"},
    {ERR_REASON(SDF_R_INVALID_KEY_LENGTH), "invalid key length"},
    {ERR_REASON(SDF_R_INVALID_OPERATION), "invalid operation"},
    {ERR_REASON(SDF_R_INVALID_PADDING), "invalid padding"},
    {ERR_REASON(SDF_R_INVALID_SIGNATURE_LENGTH), "invalid signature length"},
    {ERR_REASON(SDF_R_KEY_NOT_FOUND), "key not found"},
    {ERR_REASON(SDF_R_MISSING_KEY_COMPONENTS), "missing key components"},
    {ERR_REASON(SDF_R_NOT_LOADED), "not loaded"},
    {ERR_REASON(SDF_R_NO_MODULUS_OR_NO_EXPONENT), "no modulus or no exponent"},
    {ERR_REASON(SDF_R_OPERATION_NOT_SUPPORTED), "operation not supported"},
    {ERR_REASON(SDF_R_OUTLEN_TO_LARGE), "outlen to large"},
    {ERR_REASON(SDF_R_REQUEST_FAILED), "request failed"},
    {ERR_REASON(SDF_R_REQUEST_FALLBACK), "request fallback"},
    {ERR_REASON(SDF_R_SIZE_TOO_LARGE_OR_TOO_SMALL), "size too large or too small"},
    {ERR_REASON(SDF_R_UNIT_FAILURE), "unit failure"},
    {ERR_REASON(SDF_R_UNKNOWN_ALGORITHM_TYPE), "unknown algorithm type"},
    {ERR_REASON(SDF_R_UNKNOWN_COMMAND), "unknown command"},
    {ERR_REASON(SDF_R_UNKNOWN_DIGEST), "unknown digest"},
    {ERR_REASON(SDF_R_UNKNOWN_PADDING_TYPE), "unknown padding type"},
    {ERR_REASON(SDF_R_UNSUPPORTED_ALGORITHM_NID), "unsupported algorithm nid"},
    {ERR_REASON(SDF_R_UNSUPPORTED_PUBLIC_KEY_ALGORITHM), "unsupported public key algorithm"},
    {ERR_REASON(SDF_R_DEVICE_NOT_FOUND), "device not found"},
    {ERR_REASON(SDF_R_DEVICE_OPEN_FAILED), "device open failed"},
    {ERR_REASON(SDF_R_SESSION_OPEN_FAILED), "session open failed"},
    {ERR_REASON(SDF_R_AUTHENTICATION_FAILED), "authentication failed"},
    {ERR_REASON(SDF_R_CONTAINER_NOT_FOUND), "container not found"},
    {ERR_REASON(SDF_R_CERTIFICATE_NOT_FOUND), "certificate not found"},
    {ERR_REASON(SDF_R_PRIVATE_KEY_NOT_FOUND), "private key not found"},
    {ERR_REASON(SDF_R_PUBLIC_KEY_NOT_FOUND), "public key not found"},
    {ERR_REASON(SDF_R_SIGNATURE_VERIFICATION_FAILED), "signature verification failed"},
    {ERR_REASON(SDF_R_ENCRYPTION_FAILED), "encryption failed"},
    {ERR_REASON(SDF_R_DECRYPTION_FAILED), "decryption failed"},
    {ERR_REASON(SDF_R_HASH_CALCULATION_FAILED), "hash calculation failed"},
    {ERR_REASON(SDF_R_RANDOM_GENERATION_FAILED), "random generation failed"},
    {ERR_REASON(SDF_R_MEMORY_ALLOCATION_FAILED), "memory allocation failed"},
    {ERR_REASON(SDF_R_INVALID_PARAMETER), "invalid parameter"},
    {ERR_REASON(SDF_R_BUFFER_TOO_SMALL), "buffer too small"},
    {ERR_REASON(SDF_R_LIBRARY_NOT_INITIALIZED), "library not initialized"},
    {ERR_REASON(SDF_R_DEVICE_REMOVED), "device removed"},
    {ERR_REASON(SDF_R_PIN_INCORRECT), "pin incorrect"},
    {ERR_REASON(SDF_R_PIN_LOCKED), "pin locked"},
    {ERR_REASON(SDF_R_USER_NOT_LOGGED_IN), "user not logged in"},
    {ERR_REASON(SDF_R_OPERATION_TIMEOUT), "operation timeout"},
    {ERR_REASON(SDF_R_HARDWARE_ERROR), "hardware error"},
    {ERR_REASON(SDF_R_COMMUNICATION_ERROR), "communication error"},
    {ERR_REASON(SDF_R_INTERNAL_ERROR), "internal error"},
    {ERR_REASON(SDF_R_EXPORT_KEY_FAILED), "export key failed"},
    {ERR_REASON(SDF_R_INIT_FAILED), "init failed"},
    {ERR_REASON(SDF_R_NOT_INITIALIZED), "not initialized"},
    {ERR_REASON(SDF_R_OPEN_DEVICE_FAILED), "open device failed"},
    {ERR_REASON(SDF_R_OPEN_SESSION_FAILED), "open session failed"},
    {0, (const char *)0}
};

#endif

static int lib_code = 0;
static int error_loaded = 0;

static int ERR_load_SDF_strings(void)
{
    if (lib_code == 0)
        lib_code = ERR_get_next_error_library();

    if (!error_loaded) {
#ifndef OPENSSL_NO_ERR
        ERR_load_strings(lib_code, SDF_str_functs);
        ERR_load_strings(lib_code, SDF_str_reasons);
#endif
        error_loaded = 1;
    }
    return 1;
}

static void ERR_unload_SDF_strings(void)
{
    if (error_loaded) {
#ifndef OPENSSL_NO_ERR
        ERR_unload_strings(lib_code, SDF_str_functs);
        ERR_unload_strings(lib_code, SDF_str_reasons);
#endif
        error_loaded = 0;
    }
}

static void ERR_SDF_error(int function, int reason, const char *file, int line)
{
    if (lib_code == 0)
        lib_code = ERR_get_next_error_library();
    ERR_raise(lib_code, reason);
    ERR_set_debug(file, line, NULL);
}
