/*
 * Copyright 2024 The Tongsuo Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://github.com/Tongsuo-Project/Tongsuo/blob/master/LICENSE.txt
 */

/*
 * NOTE: this file was auto generated by the script: e_skf_err.h
 * Any changes made to this file will be overwritten when the script is next run
 */

#include <openssl/opensslconf.h>
#include <openssl/err.h>
#include <openssl/symhacks.h>
#include <openssl/crypto.h>
#include <stdlib.h>
#include "e_skf_err.h"

#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(0,func,0)
# define ERR_REASON(reason) ERR_PACK(0,0,reason)

/* SKF 函数定义 */
# define SKF_F_SKF_INIT                                   100
# define SKF_F_SKF_FINISH                                 101
# define SKF_F_SKF_CTRL                                   102
# define SKF_F_SKF_LOAD_PRIVKEY                           103
# define SKF_F_SKF_LOAD_PUBKEY                            104
# define SKF_F_SKF_RSA_SIGN                               105
# define SKF_F_SKF_RSA_PRIV_DEC                           106
# define SKF_F_SKF_ECDSA_SIGN                             107
# define SKF_F_SKF_SM2_SIGN                               108
# define SKF_F_SKF_SM2_DECRYPT                            109
# define SKF_F_SKF_RAND_BYTES                             110
# define SKF_F_SKF_LOAD_LIBRARY                           111
# define SKF_F_SKF_INIT_DEVICE                            112
# define SKF_F_SKF_ENUM_DEVICES                           113
# define SKF_F_SKF_ENUM_APPLICATIONS                      114
# define SKF_F_SKF_ENUM_CONTAINERS                        115
# define SKF_F_BIND_SKF                                   116
/* EVP_PKEY EC method function codes */
# define SKF_F_SKF_PKEY_EC_INIT                           117
# define SKF_F_SKF_PKEY_EC_COPY                           118
# define SKF_F_SKF_PKEY_EC_PARAMGEN                       119
# define SKF_F_SKF_PKEY_EC_KEYGEN                         120
# define SKF_F_SKF_PKEY_EC_SIGN                           121
# define SKF_F_SKF_PKEY_EC_VERIFY                         122
# define SKF_F_SKF_PKEY_EC_ENCRYPT                        123
# define SKF_F_SKF_PKEY_EC_DECRYPT                        124
# define SKF_F_SKF_PKEY_EC_DERIVE                         125
# define SKF_F_SKF_PKEY_EC_KDF_DERIVE                     126
# define SKF_F_SKF_PKEY_EC_CTRL                           127
# define SKF_F_SKF_PKEY_EC_CTRL_STR                       128
/* Misc helper function codes */
# define SKF_F_SKF_SET_FEATURE_MASK                       129
# define SKF_F_SKF_VALIDATE_MASK                          130
# define SKF_F_SKF_SSL_GENERATE_MASTER_SECRET             131
# define SKF_F_SKF_TLS1_GENERATE_KEY_BLOCK                132

/* SKF 错误原因定义 */
# define SKF_R_ALREADY_LOADED                             100
# define SKF_R_CANT_LOAD_SKF_MODULE                       101
# define SKF_R_CTRL_COMMAND_NOT_IMPLEMENTED               102
# define SKF_R_DSO_FAILURE                                103
# define SKF_R_ENGINE_IS_NOT_INITIALIZED                  104
# define SKF_R_FUNCTION_NOT_SUPPORTED                     105
# define SKF_R_INVALID_ARGUMENT                           106
# define SKF_R_INVALID_KEY_LENGTH                         107
# define SKF_R_INVALID_OPERATION                          108
# define SKF_R_INVALID_PARAMETER                          109
# define SKF_R_INVALID_SIGNATURE_LENGTH                   110
# define SKF_R_KEY_NOT_FOUND                              111
# define SKF_R_NOT_LOADED                                 112
# define SKF_R_OPERATION_NOT_SUPPORTED                    113
# define SKF_R_REQUEST_FAILED                             114
# define SKF_R_UNKNOWN_ALGORITHM_TYPE                     115
# define SKF_R_UNKNOWN_COMMAND                            116
# define SKF_R_UNSUPPORTED_ALGORITHM_NID                  117
# define SKF_R_DEVICE_NOT_FOUND                           118
# define SKF_R_DEVICE_OPEN_FAILED                         119
# define SKF_R_APPLICATION_NOT_FOUND                      120
# define SKF_R_APPLICATION_OPEN_FAILED                    121
# define SKF_R_CONTAINER_NOT_FOUND                        122
# define SKF_R_CONTAINER_OPEN_FAILED                      123
# define SKF_R_AUTHENTICATION_FAILED                      124
# define SKF_R_CERTIFICATE_NOT_FOUND                      125
# define SKF_R_PRIVATE_KEY_NOT_FOUND                      126
# define SKF_R_PUBLIC_KEY_NOT_FOUND                       127
# define SKF_R_SIGNATURE_VERIFICATION_FAILED              128
# define SKF_R_ENCRYPTION_FAILED                          129
# define SKF_R_DECRYPTION_FAILED                          130
# define SKF_R_HASH_CALCULATION_FAILED                    131
# define SKF_R_RANDOM_GENERATION_FAILED                   132
# define SKF_R_MEMORY_ALLOCATION_FAILED                   133
# define SKF_R_BUFFER_TOO_SMALL                           134
# define SKF_R_LIBRARY_NOT_INITIALIZED                    135
# define SKF_R_DEVICE_REMOVED                             136
# define SKF_R_PIN_INCORRECT                              137
# define SKF_R_PIN_LOCKED                                 138
# define SKF_R_USER_NOT_LOGGED_IN                         139
# define SKF_R_OPERATION_TIMEOUT                          140
# define SKF_R_HARDWARE_ERROR                             141
# define SKF_R_COMMUNICATION_ERROR                        142
# define SKF_R_INTERNAL_ERROR                             143
# define SKF_R_EXPORT_KEY_FAILED                          144
# define SKF_R_INIT_FAILED                                145
# define SKF_R_NOT_INITIALIZED                            146
# define SKF_R_ENUMERATION_FAILED                         147
# define SKF_R_NO_DEVICES_FOUND                           148
# define SKF_R_NO_APPLICATIONS_FOUND                      149
# define SKF_R_NO_CONTAINERS_FOUND                        150
# define SKF_R_APPLICATION_NAME_REQUIRED                  151
# define SKF_R_CONTAINER_NAME_REQUIRED                    152
# define SKF_R_MODULE_PATH_REQUIRED                       153
# define SKF_R_NOT_SUPPORTED                              160

static ERR_STRING_DATA SKF_str_functs[] = {
    {ERR_FUNC(SKF_F_SKF_INIT), "skf_init"},
    {ERR_FUNC(SKF_F_SKF_FINISH), "skf_finish"},
    {ERR_FUNC(SKF_F_SKF_CTRL), "skf_ctrl"},
    {ERR_FUNC(SKF_F_SKF_LOAD_PRIVKEY), "skf_load_privkey"},
    {ERR_FUNC(SKF_F_SKF_LOAD_PUBKEY), "skf_load_pubkey"},
    {ERR_FUNC(SKF_F_SKF_RSA_SIGN), "skf_rsa_sign"},
    {ERR_FUNC(SKF_F_SKF_RSA_PRIV_DEC), "skf_rsa_priv_dec"},
    {ERR_FUNC(SKF_F_SKF_ECDSA_SIGN), "skf_ecdsa_sign"},
    {ERR_FUNC(SKF_F_SKF_SM2_SIGN), "skf_sm2_sign"},
    {ERR_FUNC(SKF_F_SKF_SM2_DECRYPT), "skf_sm2_decrypt"},
    {ERR_FUNC(SKF_F_SKF_RAND_BYTES), "skf_rand_bytes"},
    {ERR_FUNC(SKF_F_SKF_LOAD_LIBRARY), "skf_load_library"},
    {ERR_FUNC(SKF_F_SKF_INIT_DEVICE), "skf_init_device"},
    {ERR_FUNC(SKF_F_SKF_ENUM_DEVICES), "skf_enum_devices"},
    {ERR_FUNC(SKF_F_SKF_ENUM_APPLICATIONS), "skf_enum_applications"},
    {ERR_FUNC(SKF_F_SKF_ENUM_CONTAINERS), "skf_enum_containers"},
    {ERR_FUNC(SKF_F_BIND_SKF), "bind_skf"},
    {ERR_FUNC(SKF_F_SKF_PKEY_EC_INIT), "skf_pkey_ec_init"},
    {ERR_FUNC(SKF_F_SKF_PKEY_EC_COPY), "skf_pkey_ec_copy"},
    {ERR_FUNC(SKF_F_SKF_PKEY_EC_PARAMGEN), "skf_pkey_ec_paramgen"},
    {ERR_FUNC(SKF_F_SKF_PKEY_EC_KEYGEN), "skf_pkey_ec_keygen"},
    {ERR_FUNC(SKF_F_SKF_PKEY_EC_SIGN), "skf_pkey_ec_sign"},
    {ERR_FUNC(SKF_F_SKF_PKEY_EC_VERIFY), "skf_pkey_ec_verify"},
    {ERR_FUNC(SKF_F_SKF_PKEY_EC_ENCRYPT), "skf_pkey_ec_encrypt"},
    {ERR_FUNC(SKF_F_SKF_PKEY_EC_DECRYPT), "skf_pkey_ec_decrypt"},
    {ERR_FUNC(SKF_F_SKF_PKEY_EC_DERIVE), "skf_pkey_ec_derive"},
    {ERR_FUNC(SKF_F_SKF_PKEY_EC_KDF_DERIVE), "skf_pkey_ec_kdf_derive"},
    {ERR_FUNC(SKF_F_SKF_PKEY_EC_CTRL), "skf_pkey_ec_ctrl"},
    {ERR_FUNC(SKF_F_SKF_PKEY_EC_CTRL_STR), "skf_pkey_ec_ctrl_str"},
    {ERR_FUNC(SKF_F_SKF_SET_FEATURE_MASK), "skf_set_feature_mask"},
    {ERR_FUNC(SKF_F_SKF_VALIDATE_MASK), "skf_validate_mask"},
    {ERR_FUNC(SKF_F_SKF_SSL_GENERATE_MASTER_SECRET), "skf_ssl_generate_master_secret"},
    {ERR_FUNC(SKF_F_SKF_TLS1_GENERATE_KEY_BLOCK), "skf_tls1_generate_key_block"},
    {0, (const char *)0}
};

static ERR_STRING_DATA SKF_str_reasons[] = {
    {ERR_REASON(SKF_R_ALREADY_LOADED), "already loaded"},
    {ERR_REASON(SKF_R_CANT_LOAD_SKF_MODULE), "can't load skf module"},
    {ERR_REASON(SKF_R_CTRL_COMMAND_NOT_IMPLEMENTED), "ctrl command not implemented"},
    {ERR_REASON(SKF_R_DSO_FAILURE), "dso failure"},
    {ERR_REASON(SKF_R_ENGINE_IS_NOT_INITIALIZED), "engine is not initialized"},
    {ERR_REASON(SKF_R_FUNCTION_NOT_SUPPORTED), "function not supported"},
    {ERR_REASON(SKF_R_INVALID_ARGUMENT), "invalid argument"},
    {ERR_REASON(SKF_R_INVALID_KEY_LENGTH), "invalid key length"},
    {ERR_REASON(SKF_R_INVALID_OPERATION), "invalid operation"},
    {ERR_REASON(SKF_R_INVALID_PARAMETER), "invalid parameter"},
    {ERR_REASON(SKF_R_INVALID_SIGNATURE_LENGTH), "invalid signature length"},
    {ERR_REASON(SKF_R_KEY_NOT_FOUND), "key not found"},
    {ERR_REASON(SKF_R_NOT_LOADED), "not loaded"},
    {ERR_REASON(SKF_R_OPERATION_NOT_SUPPORTED), "operation not supported"},
    {ERR_REASON(SKF_R_REQUEST_FAILED), "request failed"},
    {ERR_REASON(SKF_R_UNKNOWN_ALGORITHM_TYPE), "unknown algorithm type"},
    {ERR_REASON(SKF_R_UNKNOWN_COMMAND), "unknown command"},
    {ERR_REASON(SKF_R_UNSUPPORTED_ALGORITHM_NID), "unsupported algorithm nid"},
    {ERR_REASON(SKF_R_DEVICE_NOT_FOUND), "device not found"},
    {ERR_REASON(SKF_R_DEVICE_OPEN_FAILED), "device open failed"},
    {ERR_REASON(SKF_R_APPLICATION_NOT_FOUND), "application not found"},
    {ERR_REASON(SKF_R_APPLICATION_OPEN_FAILED), "application open failed"},
    {ERR_REASON(SKF_R_CONTAINER_NOT_FOUND), "container not found"},
    {ERR_REASON(SKF_R_CONTAINER_OPEN_FAILED), "container open failed"},
    {ERR_REASON(SKF_R_AUTHENTICATION_FAILED), "authentication failed"},
    {ERR_REASON(SKF_R_CERTIFICATE_NOT_FOUND), "certificate not found"},
    {ERR_REASON(SKF_R_PRIVATE_KEY_NOT_FOUND), "private key not found"},
    {ERR_REASON(SKF_R_PUBLIC_KEY_NOT_FOUND), "public key not found"},
    {ERR_REASON(SKF_R_SIGNATURE_VERIFICATION_FAILED), "signature verification failed"},
    {ERR_REASON(SKF_R_ENCRYPTION_FAILED), "encryption failed"},
    {ERR_REASON(SKF_R_DECRYPTION_FAILED), "decryption failed"},
    {ERR_REASON(SKF_R_HASH_CALCULATION_FAILED), "hash calculation failed"},
    {ERR_REASON(SKF_R_RANDOM_GENERATION_FAILED), "random generation failed"},
    {ERR_REASON(SKF_R_MEMORY_ALLOCATION_FAILED), "memory allocation failed"},
    {ERR_REASON(SKF_R_BUFFER_TOO_SMALL), "buffer too small"},
    {ERR_REASON(SKF_R_LIBRARY_NOT_INITIALIZED), "library not initialized"},
    {ERR_REASON(SKF_R_DEVICE_REMOVED), "device removed"},
    {ERR_REASON(SKF_R_PIN_INCORRECT), "pin incorrect"},
    {ERR_REASON(SKF_R_PIN_LOCKED), "pin locked"},
    {ERR_REASON(SKF_R_USER_NOT_LOGGED_IN), "user not logged in"},
    {ERR_REASON(SKF_R_OPERATION_TIMEOUT), "operation timeout"},
    {ERR_REASON(SKF_R_HARDWARE_ERROR), "hardware error"},
    {ERR_REASON(SKF_R_COMMUNICATION_ERROR), "communication error"},
    {ERR_REASON(SKF_R_INTERNAL_ERROR), "internal error"},
    {ERR_REASON(SKF_R_EXPORT_KEY_FAILED), "export key failed"},
    {ERR_REASON(SKF_R_INIT_FAILED), "init failed"},
    {ERR_REASON(SKF_R_NOT_INITIALIZED), "not initialized"},
    {ERR_REASON(SKF_R_ENUMERATION_FAILED), "enumeration failed"},
    {ERR_REASON(SKF_R_NO_DEVICES_FOUND), "no devices found"},
    {ERR_REASON(SKF_R_NO_APPLICATIONS_FOUND), "no applications found"},
    {ERR_REASON(SKF_R_NO_CONTAINERS_FOUND), "no containers found"},
    {ERR_REASON(SKF_R_APPLICATION_NAME_REQUIRED), "application name required"},
    {ERR_REASON(SKF_R_CONTAINER_NAME_REQUIRED), "container name required"},
    {ERR_REASON(SKF_R_MODULE_PATH_REQUIRED), "module path required"},
    {ERR_REASON(SKF_R_NOT_SUPPORTED), "not supported"},
    {0, (const char *)0}
};

#endif

static int lib_code = 0;
static int error_loaded = 0;

static int ERR_load_SKF_strings(void)
{
    if (lib_code == 0)
        lib_code = ERR_get_next_error_library();

    if (!error_loaded) {
#ifndef OPENSSL_NO_ERR
        ERR_load_strings(lib_code, SKF_str_functs);
        ERR_load_strings(lib_code, SKF_str_reasons);
#endif
        error_loaded = 1;
    }
    return 1;
}

static void ERR_unload_SKF_strings(void)
{
    if (error_loaded) {
#ifndef OPENSSL_NO_ERR
        ERR_unload_strings(lib_code, SKF_str_functs);
        ERR_unload_strings(lib_code, SKF_str_reasons);
#endif
        error_loaded = 0;
    }
}

static void ERR_SKF_error(int function, int reason, char *file, int line)
{
    if (lib_code == 0)
        lib_code = ERR_get_next_error_library();
    ERR_PUT_error(lib_code, function, reason, file, line);
}